/**
* @param key is a key generated by MapReduce framework
* @param value is a partitioned FASTQ file (may be 8M lines = 2M sequences)
*/

map(key, value) {
// note: chr23 = concat(chrX, chrY, chrM)
alignedBAMFile = alignByBWA(value);
(chr1File, chr2File, ..., ch23File) = partitionByChromosome(alignedFile);
for (i=1, i < 24; i++) {
    emit(chr<i>, chr<i>File);
}
